services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    profiles:  ## docker composeの対象から外す
      - api

  db:
    image: mysql:9.7
    restart: always
    container_name: quiz-db
    environment:
      MYSQL_DATABASE: quiz_app
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: