"""create exam table

Revision ID: 0f18fabe7ff8
Revises: 4af80c0e98ca
Create Date: 2026-06-13 18:46:46.684968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f18fabe7ff8'
down_revision: Union[str, Sequence[str], None] = '4af80c0e98ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams')),
    sa.UniqueConstraint('name', name=op.f('uq_exams_name')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('questions', sa.Column('exam_id', mysql.BIGINT(unsigned=True), nullable=False))
    op.create_foreign_key(op.f('fk_questions_exam_id_exams'), 'questions', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_questions_exam_id_exams'), 'questions', type_='foreignkey')
    op.drop_column('questions', 'exam_id')
    op.drop_table('exams')
    # ### end Alembic commands ###
