"""change questions column

Revision ID: 4af80c0e98ca
Revises: ccc9f12e2191
Create Date: 2026-06-08 20:06:29.845210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4af80c0e98ca'
down_revision: Union[str, Sequence[str], None] = 'ccc9f12e2191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_text',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_text',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
